### ISSUE TITLE
Add support for tokio::timer::timeout::Timeout?

### ISSUE THREAD

**Issue by nerdrew** [srijs/rust-tokio-retry#11]
It looks like tokio_timer is deprecated. Is it possible to add support for [tokio::timer::timout::Timeout](https://docs.rs/tokio/0.1.15/tokio/timer/timeout/struct.Timeout.html) instead?

**Comment by srijs** [comment]
Hi!

Where did you get the impression that `tokio-timer` was deprecated? The `tokio` crate is a facade that pulls in smaller crates including `tokio-timer`.

If you depend directly on `tokio`, `tokio::timer::timeout::Timeout` should be a re-export of `tokio_timer::timeout::Timeout`.

**Comment by nerdrew** [comment]
DOH!. My bad. I looked at https://github.com/tokio-rs/tokio-timer and mis-read the deprecation warning. Ignore me!

**Comment by srijs** [comment]
No problem!
