### ISSUE TITLE
limit_retries with ExponentialBackoff

### ISSUE THREAD

**Issue by bbigras** [srijs/rust-tokio-retry#2]
Is it still possible to use limit_retries with ExponentialBackoff?

I would like an exponential back off but only for a couple of retries.

**Comment by srijs** [comment]
Hi!

Yes, that should be still possible.

Out of curiosity, what made you think otherwise?

**Comment by bbigras** [comment]
I wasn't able to run the sample from the readme with the master branch.

```
error[E0432]: unresolved import `tokio_retry::RetryStrategy`
 --> src/main.rs:9:5
  |
9 | use tokio_retry::RetryStrategy;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `RetryStrategy` in the root

error[E0432]: unresolved import `tokio_retry::strategies::ExponentialBackoff`
  --> src/main.rs:10:5
   |
10 | use tokio_retry::strategies::ExponentialBackoff;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `strategies` in `tokio_retry`

error: aborting due to 2 previous errors

error: Could not compile `test-retry`.
```

I managed to run it but `limit_retries()` and `limit_delay()` doesn't seem to exist anymore.

**Comment by srijs** [comment]
I updated the readme with an up-to-date example. Let me know if it works for you!

**Comment by bbigras** [comment]
I'm not sure. In my test it seems to retry too quickly but maybe I'm doing something wrong.

I think it would be a good idea to change the sample in the readme to demonstrate a couple of retires with a timestamp like my code tries to do.

```rust
extern crate futures;
extern crate tokio_timer;
extern crate tokio_retry;
extern crate time;

use futures::Future;
use tokio_timer::Timer;
use tokio_retry::RetryFuture;
use tokio_retry::strategy::{ExponentialBackoff, jitter};
use time::now;

fn action() -> Result<u64, ()> {
    println!("{}: test", now().strftime("%H:%M:%S.%f").unwrap());
    Err(())
}

pub fn main() {
    let retry_strategy = ExponentialBackoff::from_millis(10).map(jitter).take(3);
    let retry_future = RetryFuture::spawn(Timer::default(), retry_strategy, action);
    let retry_result = retry_future.wait();

    assert!(retry_result.is_err());
}
```

```
09:50:47.047384610: test
09:50:47.047876291: test
09:50:47.047904782: test
09:50:48.047142413: test
```

**Comment by srijs** [comment]
I'll look into that tomorrow (it's already late here in Sydney).

Please note that `.map(jitter)` will cause full random jitter to be applied to the duration, so you might want to test without that first. There might however be a bug in the jitter function, will be able to provide more insight tomorrow.

**Comment by srijs** [comment]
I looked into the issue today. The main insight I got was that `tokio_timer::Timer` is extremely imprecise for sub-second timeouts, and `tokio_core::reactor::Handle` gives much better precision. In comparison, using an exponential back-off starting at 10 ms without jitter:

Using `tokio_timer::Timer` (similar results to what you observed):

```
Expected Duration { secs: 0, nanos: 880531 }
Actual Duration   { secs: 0, nanos: 1242384 }
Expected Duration { secs: 0, nanos: 32900206 }
Actual Duration   { secs: 0, nanos: 30661 }
Expected Duration { secs: 1, nanos: 0 }
Actual Duration   { secs: 1, nanos: 504134 }
```

Using `tokio_core::reactor::Handle`:

```
Expected Duration { secs: 0, nanos: 7760758 }
Actual Duration   { secs: 0, nanos: 9801332 }
Expected Duration { secs: 0, nanos: 76257389 }
Actual Duration   { secs: 0, nanos: 78253005 }
Expected Duration { secs: 1, nanos: 0 }
Actual Duration   { secs: 1, nanos: 804152 }
```

I changed the example in the README to use `tokio_core`, and will add a section about this to the readme soon.

Hope that helps.

Let me know if you run into any other problems.
