### ISSUE TITLE
Is it possible to have an FnOnce action closure

### ISSUE THREAD

**Issue by ppoliani** [srijs/rust-tokio-retry#21]
In the code there is a trait bound that suggests that the action closure needs to be na FnMut. Is there a reason an FnOnce could not be used instead?

**Comment by srijs** [comment]
Hi! Given that the action will be executed one or more times, it needs to be at least `FnMut` for this to work. `FnOnce` will cause the closure to be consumed on the first execution, which prevents re-running the action on retry. Hope that helps!

**Comment by ppoliani** [comment]
Oh of course, that make sense. Thanks for explaining this
