### ISSUE TITLE
Support for the new tokio crate

### ISSUE THREAD

**Issue by alekseysidorov** [srijs/rust-tokio-retry#7]
At the moment the `tokio-retry` is based on top of [`tokio-core`](https://crates.io/crates/tokio-core). But it has a modern replacement [`tokio`](https://crates.io/crates/tokio)

What do you think about porting crate to `tokio`?

**Comment by srijs** [comment]
Sounds good to me!

I was originally going to wait until futures 0.2 lands, but there shouldn’t be a reason why we couldn’t do a new breaking release in the meantime if there is demand for it!

**Comment by srijs** [comment]
Published as `tokio-retry` 0.2.0 (https://crates.io/crates/tokio-retry) 🎉
